# 制御ループ周波数
hz: 10              # ループ周波数[Hz]

# 目標軌道
radius: 1.0         # 軌道の旋回半径[m]
cource_length: 20   # x軸方向の長さ[m]
resolution: 0.1     # 軌道生成時の刻み幅[m]

# 初期位置
init_x: 2.0         # x座標[m]
init_y: 0.3         # y座標[m]
init_theta: 0.75     # 生成する軌道の向き[rad]
